# Site settings
title: Geekmonks Blog
email: no-reply@geekmonks.com
description: >- # this means to ignore newlines until "baseurl:"
  Learn, share and grow together.

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Jekyll Remote Theme configuration
remote_theme: "pages-themes/minima@v0.2.0"

# Exclude from processing.
# The following items will not be processed, by default.
# For example, they will not be copied to the output directory.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
