# Site settings
title: Geekmonks Blog
email: no-reply@geekmonks.com
description: >- # this means to ignore newlines until "baseurl:"
  Learn, share and grow together.

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Tell Jekyll not to use a theme
# This is crucial for builds to work with your custom layout.
theme: null

# 
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"